# Copyright (C) Pipin Fitriadi - All Rights Reserved

# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Pipin Fitriadi <pipinfitriadi@gmail.com>, 11 December 2025

name: CI/CD
on:
  push:
    branches: ['**']
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[a-z]+'
      - '[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'
    paths:
      - '**/*.ipynb'
      - '**/*.py'
      - tests/**/*
      - pyproject.toml
  workflow_dispatch:
    inputs:
      codecoverage-percentage-passed:
        description: Percentage as an integer for passing code coverage
        type: number
        default: 100
        required: true
jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    env:
      PIP_ROOT_USER_ACTION: ignore
      PIP_DISABLE_PIP_VERSION_CHECK: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install --editable '.[cli, cryptography, database, http, not_supported_by_vercel, storage]' --group code-quality
      - name: Test
        run: |
          ruff check --preview --select E,E305
          ruff check
  code-coverage:
    name: Code Coverage
    if:
      github.ref_type == 'tag' ||
      contains('refs/heads/main', github.ref) ||
      startsWith(github.ref, 'refs/heads/release/') ||
      startsWith(github.ref, 'refs/heads/hotfix/')
    runs-on: ubuntu-latest
    env:
      PIP_ROOT_USER_ACTION: ignore
      PIP_DISABLE_PIP_VERSION_CHECK: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install --editable '.[cli, cryptography, database, http, not_supported_by_vercel, storage]' --group code-coverage
      - name: Test
        run: coverage run -m pytest -rfEP -q --junit-xml=code-coverage.xml
      - name: Display coverage
        run: coverage report -m
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Publish coverage report
        uses: mikepenz/action-junit-report@v6
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: code-coverage.xml
          annotate_only: true
      - name: Percentage passed
        run: if [ $(printf '%.0f' $(coverage report | awk '$1 == "TOTAL" {print $NF+0}')) -ge ${{ github.event.inputs.codecoverage-percentage-passed || 100 }} ]; then exit; else exit 1; fi
  release:
    name: Release
    needs: [code-quality, code-coverage]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    env:
      PIP_ROOT_USER_ACTION: ignore
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      name: python
      url: https://pypi.org/project/${{ github.event.repository.name }}
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install build
      - name: Build package
        run: python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
